### ISSUE TITLE
head CSS Style tag

### ISSUE THREAD

**Issue by R4xx4r** [Domi236/playground#5]
Please try to avoid things  like this in the header
```css
<style>
    * {
      box-sizing: border-box;
    }
    html {
      font-family: sans-serif, serif;
      font-size: 16px;
      scroll-behavior: smooth;
    }
    body {
      margin: 0;
    }
</style>
```
and put it to external css files
